plugins {
    id 'java'
    id "com.github.node-gradle.node" version "7.1.0" apply false
    id "io.freefair.lombok" version "9.2.0"
    id "run.halo.plugin.devtools" version "0.8.0"
}

group 'run.halo.editor.hyperlink'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('run.halo.tools.platform:plugin:2.22.11')
    compileOnly 'run.halo.app:api'

    testImplementation 'run.halo.app:api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

sourceSets.main.resources.exclude 'console/**', 'static/**'

tasks.named('processResources', Copy) {
    dependsOn project(':packages').tasks.named('pnpmBuild')
    from(project(':packages').layout.projectDirectory.dir('ui/build/dist')) {
        into 'console'
    }
    from(project(':packages').layout.projectDirectory.dir('hyperlink-card/dist')) {
        include 'index.iife.js', 'index.css'
        into 'static'
    }
    doFirst {
        delete layout.buildDirectory.dir('resources/main/console'),
            layout.buildDirectory.dir('resources/main/static')
    }
}

halo {
    version = '2.22'
    debug = true
}
