name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v5
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      node-version: "24"
      pnpm-version: "12.4.2"
      java-version: "21"
      app-id: app-UpUJA
      skip-node-setup: false
      ui-path: "packages"
      sync-github-readme: true
